# this file contains properties that are used for technical purpose and are not part of translation like i18n

#icons
scanBtnIcon=sap-icon://bar-code
refreshBtnIcon=sap-icon://refresh
confirmBtnIcon=sap-icon://show-edit

# others
delaySetCursorMs = 500